---
abstract: 'Parsing and manipulating ELAN files'
author:
  - 'Simon Cozens <simon@simon-cozens.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-ELAN
no_index:
  directory:
    - t
    - inc
requires:
  XML::LibXML: 0
  perl: 5.006
version: 0.01
